2013/12/02 17:30:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'usrCrediTaxi'@'localhost' (using password: YES)' in C:\xampp\htdocs\creditaxi\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\xampp\htdocs\creditaxi\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\creditaxi\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\creditaxi\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\creditaxi\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\creditaxi\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 C:\xampp\htdocs\creditaxi\framework\web\CFormModel.php(39): CrudCode->init()
#6 C:\xampp\htdocs\creditaxi\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\creditaxi\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\creditaxi\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\creditaxi\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\creditaxi\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\creditaxi\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\creditaxi\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\xampp\htdocs\creditaxi\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud')
#14 C:\xampp\htdocs\creditaxi\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\creditaxi\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/creditaxi/gii/crud
HTTP_REFERER=http://localhost/creditaxi/gii/default/index
---
